### ISSUE TITLE
Latency

### ISSUE THREAD

**Issue by foysal-ahamed** [M0r13n/mikrotik_monitoring#22]
By default added 3 ips to check those ips latency, but I need more ip to add and check latency. How can I add?

**Comment by M0r13n** [comment]
@foysal-ahamed You need to adapt the targets in [prometheus/prometheus.yml](https://github.com/M0r13n/mikrotik_monitoring/blob/7fb2f026349f4622c6f1e49c3be225af3f090853/prometheus/prometheus.yml#L40)

```yaml
    static_configs:
      - targets:
        - 1.1.1.1
        - 8.8.8.8
        - 9.9.9.9
        - 10.0.0.1
```
